package com.cadence.codingassessmentservice.exception;

public enum ErrorCode {
    ASSESSMENT_NOT_FOUND,
    ASSESSMENT_NOT_DRAFT,
    ASSESSMENT_ALREADY_PUBLISHED,
    QUESTION_NOT_FOUND,
    CANDIDATE_ASSESSMENT_NOT_FOUND,
    ASSESSMENT_ALREADY_STARTED,
    ASSESSMENT_NOT_IN_PROGRESS,
    ASSESSMENT_ALREADY_COMPLETED,
    ASSESSMENT_EXPIRED,
    RULES_NOT_ACCEPTED,
    SUBMISSION_NOT_FOUND,
    EXECUTION_FAILED,
    CANDIDATE_NOT_FOUND,
    JOB_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
