package com.cadence.applicationservice.exception;

public enum ErrorCode {
    APPLICATION_NOT_FOUND,
    JOB_NOT_FOUND,
    CANDIDATE_NOT_FOUND,
    COMPANY_NOT_FOUND,
    DUPLICATE_APPLICATION,
    JOB_NOT_PUBLISHED,
    APPLICATION_DEADLINE_PASSED,
    CANDIDATE_PROFILE_INCOMPLETE,
    RESUME_NOT_FOUND,
    APPLICATION_NOT_WITHDRAWABLE,
    INVALID_STATUS_TRANSITION,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
