package com.cadence.jobservice.exception;

public enum ErrorCode {
    JOB_NOT_FOUND,
    DUPLICATE_JOB_CODE,
    INVALID_STATUS_TRANSITION,
    PAST_APPLICATION_DEADLINE,
    INVALID_SALARY_RANGE,
    INVALID_EXPERIENCE_RANGE,
    INVALID_OPENINGS,
    PIPELINE_STAGE_NOT_FOUND,
    TEMPLATE_NOT_FOUND,
    JOB_NOT_READY_TO_PUBLISH,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
