package com.cadence.interviewmanagementservice.exception;

public enum ErrorCode {
    INTERVIEW_ROUND_NOT_FOUND,
    INTERVIEW_NOT_FOUND,
    INTERVIEW_ALREADY_COMPLETED,
    INTERVIEW_ALREADY_CANCELLED,
    INTERVIEW_NOT_COMPLETABLE,
    FEEDBACK_ALREADY_SUBMITTED,
    NOT_A_PANELIST,
    CANDIDATE_NOT_FOUND,
    JOB_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    COMPANY_NOT_FOUND,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
