package com.cadence.authservice.exception;

public enum ErrorCode {
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,
    EMAIL_NOT_VERIFIED,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    MFA_REQUIRED,
    INVALID_MFA_CODE,
    MFA_ALREADY_ENABLED,
    MFA_NOT_ENABLED,
    ROLE_NOT_FOUND,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
