package com.cadence.candidateservice.exception;

public enum ErrorCode {
    CANDIDATE_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    JOB_NOT_FOUND,
    JOB_NOT_PUBLISHED,
    DUPLICATE_APPLICATION,
    APPLICATION_NOT_WITHDRAWABLE,
    INVALID_STATUS_TRANSITION,
    JOB_ALREADY_SAVED,
    SAVED_JOB_NOT_FOUND,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
