package com.cadence.companyservice.exception;

public enum ErrorCode {
    COMPANY_NOT_FOUND,
    DEPARTMENT_NOT_FOUND,
    OFFICE_NOT_FOUND,
    TEAM_INVITATION_NOT_FOUND,
    DUPLICATE_COMPANY_NAME,
    DUPLICATE_COMPANY_SLUG,
    DUPLICATE_DEPARTMENT_NAME,
    DUPLICATE_PENDING_INVITATION,
    INVITATION_EXPIRED,
    INVITATION_NOT_PENDING,
    INVALID_INVITE_TOKEN,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
