package com.cadence.offermanagementservice.exception;

public enum ErrorCode {
    OFFER_NOT_FOUND,
    OFFER_DOCUMENT_NOT_FOUND,
    OFFER_NEGOTIATION_NOT_FOUND,
    OFFER_NOT_EDITABLE,
    OFFER_NOT_APPROVABLE,
    OFFER_NOT_SENDABLE,
    OFFER_NOT_WITHDRAWABLE,
    OFFER_NOT_RESPONDABLE,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
