package com.cadence.authservice.constant;

public enum AuditEventType {
    REGISTER,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    TOKEN_REFRESH,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_SUCCESS,
    PASSWORD_CHANGED,
    EMAIL_VERIFIED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_CHALLENGE_SUCCESS,
    MFA_CHALLENGE_FAILURE,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    SESSION_REVOKED
}
