package com.cadence.notificationservice.constants;

/** The unique business code identifying a specific template -- the real lookup key at render time (several templates can share one TriggerEvent, e.g. USER_REGISTERED branches into CANDIDATE_REGISTRATION vs WELCOME_EMAIL by this code). */
public enum TemplateCategory {
    RECRUITER_INVITATION,
    CANDIDATE_REGISTRATION,
    WELCOME_EMAIL,
    EMAIL_VERIFICATION,
    PASSWORD_RESET,
    APPLICATION_RECEIVED,
    RESUME_UPLOADED,
    RESUME_SHORTLISTED,
    RESUME_REJECTED,
    AI_INTERVIEW_INVITATION,
    AI_INTERVIEW_REMINDER,
    CODING_ASSESSMENT_INVITATION,
    CODING_ASSESSMENT_REMINDER,
    TECHNICAL_INTERVIEW_INVITATION,
    TECHNICAL_INTERVIEW_REMINDER,
    HR_INTERVIEW_INVITATION,
    HR_INTERVIEW_REMINDER,
    INTERVIEW_RESCHEDULED,
    INTERVIEW_CANCELLED,
    OFFER_LETTER,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    BACKGROUND_VERIFICATION
}
