package com.cadence.aiinterviewservice.exception;

public enum ErrorCode {
    SHORTLIST_NOT_FOUND,
    INTERVIEW_NOT_FOUND,
    INTERVIEW_ALREADY_STARTED,
    INTERVIEW_NOT_IN_PROGRESS,
    INTERVIEW_ALREADY_COMPLETED,
    INTERVIEW_EXPIRED,
    QUESTION_NOT_FOUND,
    CANDIDATE_NOT_FOUND,
    JOB_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
