package com.cadence.resumeparserservice.exception;

public enum ErrorCode {
    RESUME_NOT_FOUND,
    CANDIDATE_NOT_FOUND,
    CANDIDATE_NOT_ACTIVE,
    PARSING_NOT_FAILED,
    PARSING_ALREADY_IN_PROGRESS,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    INTERNAL_ERROR,
    MATCH_NOT_FOUND,
    MATCH_ALREADY_IN_PROGRESS,
    APPLICATION_NOT_FOUND,
    JOB_NOT_FOUND
}
